version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./my-laravel-app/nginx.conf:/etc/nginx/nginx.conf
      - ./my-laravel-app/public:/var/www/html/public
    depends_on:
      - app

  app:
    build: ./my-laravel-app
    volumes:
      - ./my-laravel-app:/var/www/html

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: fileRouge
      MYSQL_DATABASE: fileRouge
      MYSQL_USER: fileRouge
      MYSQL_PASSWORD: fileRouge
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=fileRouge
    ports:
      - '8071:80'
    depends_on:
      - mysql

volumes:
  mysql_data:
